# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('marital', models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('O', 'Other')], max_length=1)),
                ('age', models.IntegerField()),
                ('job', models.CharField(choices=[('ex', 'Executive'), ('ho', 'Hospitality'), ('ot', 'Other'), ('pr', 'Professional'), ('re', 'Retail'), ('rr', 'Retired'), ('sa', 'Sales'), ('st', 'Student'), ('tr', 'Trades')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
            ],
        ),
    ]
