# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170509_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='camping_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawprediction', models.CharField(max_length=2000)),
                ('product', models.CharField(max_length=30)),
                ('prediction', models.FloatField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='results',
            name='person',
        ),
        migrations.DeleteModel(
            name='results',
        ),
    ]
