# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170509_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('notes', models.TextField()),
            ],
        ),
    ]
