# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_api_params_service_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_params',
            name='api_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='api_params',
            name='endpoint',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='api_params',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='api_params',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='api_params',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='api_params',
            name='version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
