# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_demos_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHeroFight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SuperHeroOne', models.IntegerField(choices=[[0, 'Scarlet Witch'], [1, 'Jean Grey'], [2, 'Dr. Doom'], [3, 'Magik'], [4, 'Vision'], [5, 'Black Panther'], [6, 'Capt. America'], [7, 'Doctor Strange'], [8, 'Silver Surfer'], [9, 'Cable'], [10, 'Thor'], [11, 'Iceman'], [12, 'Loki'], [13, 'War Machine'], [14, 'Kitty Pryde'], [15, 'Invisible Woman'], [16, 'Rocket Raccoon'], [17, 'Punisher'], [18, 'Spiderman'], [19, 'Rogue'], [20, 'Thing'], [21, 'Venom'], [22, 'Blade'], [23, 'Cyclops'], [24, 'Nova'], [25, 'She Hulk'], [26, 'Iron Man'], [27, 'Ms. Marvel'], [28, 'Gambit'], [29, 'Antman'], [30, 'Taskmaster'], [31, 'Hulk'], [32, 'Mr. Fantastic'], [33, 'Moon Knight'], [34, 'Psylocke'], [35, 'Winter Soldier'], [36, 'Ghost Rider'], [37, 'Juggernaut'], [38, 'Hawkeye'], [39, 'Human Torch'], [40, 'Iron Fist'], [41, 'Black Widow'], [42, 'Storm'], [43, 'Emma Frost'], [44, 'Wolverine'], [45, 'Luke Cage'], [46, 'Daredevil'], [47, 'X23'], [48, 'Magneto'], [49, 'Nightcrawler'], [50, 'Colossus'], [51, 'Starlord'], [52, 'Squirrel Girl'], [53, 'Deadpool']])),
                ('heroone_score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('SuperHeroTwo', models.IntegerField(choices=[[0, 'Scarlet Witch'], [1, 'Jean Grey'], [2, 'Dr. Doom'], [3, 'Magik'], [4, 'Vision'], [5, 'Black Panther'], [6, 'Capt. America'], [7, 'Doctor Strange'], [8, 'Silver Surfer'], [9, 'Cable'], [10, 'Thor'], [11, 'Iceman'], [12, 'Loki'], [13, 'War Machine'], [14, 'Kitty Pryde'], [15, 'Invisible Woman'], [16, 'Rocket Raccoon'], [17, 'Punisher'], [18, 'Spiderman'], [19, 'Rogue'], [20, 'Thing'], [21, 'Venom'], [22, 'Blade'], [23, 'Cyclops'], [24, 'Nova'], [25, 'She Hulk'], [26, 'Iron Man'], [27, 'Ms. Marvel'], [28, 'Gambit'], [29, 'Antman'], [30, 'Taskmaster'], [31, 'Hulk'], [32, 'Mr. Fantastic'], [33, 'Moon Knight'], [34, 'Psylocke'], [35, 'Winter Soldier'], [36, 'Ghost Rider'], [37, 'Juggernaut'], [38, 'Hawkeye'], [39, 'Human Torch'], [40, 'Iron Fist'], [41, 'Black Widow'], [42, 'Storm'], [43, 'Emma Frost'], [44, 'Wolverine'], [45, 'Luke Cage'], [46, 'Daredevil'], [47, 'X23'], [48, 'Magneto'], [49, 'Nightcrawler'], [50, 'Colossus'], [51, 'Starlord'], [52, 'Squirrel Girl'], [53, 'Deadpool']])),
                ('herotwo_score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='api_params',
            new_name='ApiParameters',
        ),
    ]
