# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_superhero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='Fights',
            field=models.IntegerField(),
        ),
    ]
