# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170531_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='Fights',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
