# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170606_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superherofight',
            name='home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='superherofight',
            name='night',
            field=models.BooleanField(default=False),
        ),
    ]
