# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name_text',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(choices=[[20, 20], [25, 25], [30, 30], [35, 35], [40, 40], [45, 45], [50, 50], [55, 55], [60, 60], [65, 65]]),
        ),
    ]
