# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170509_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camping_results',
            name='rawprediction',
            field=models.TextField(),
        ),
    ]
