# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_api_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_params',
            name='api_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
